name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: github-actions[bot]
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "$GIT_USER"
          git config --global user.email "$GIT_EMAIL"
          npx gh-pages -d dist -u "$GIT_USER <$GIT_EMAIL>" -r https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
